### ISSUE TITLE
Top post of Month/Week

### ISSUE THREAD

**Issue by jjluczyn** [Albert017/daw#11]

**Comment by helogargon** [comment]
He intentado hacer las consultas pero me sale error. Lo he puesto entre comentarios lo del repositorio y lo del index.controller. He creado tres nuevos atributos dia, mes y año para poder consultar con ellos (en Post). Creadas tres consultas (entre comentarios en postRepository) y en indexController donde se cargan los post por primera vez, en el primer método creo; añadidas lineas que están entre comentarios para cargar los modelos.

**Comment by helogargon** [comment]
PD: no funciona

**Comment by ElenaMateos193** [comment]
Todo hecho. A lo mejor hay un link que se me haya pasado, pero creo que no.
