### ISSUE TITLE
Clear unused links (navbar and others)

### ISSUE THREAD

**Issue by jjluczyn** [Albert017/daw#12]

**Comment by ElenaMateos193** [comment]
I'm about to fix changeAvatar and changeHeader links.

**Comment by helogargon** [comment]
He hecho operativa la pagina de trending ordenandome los post por votos

**Comment by helogargon** [comment]
voy a poner el enlace en todas las paginas

**Comment by helogargon** [comment]
Añadido acceso y funcionalidad a pestaña random

**Comment by helogargon** [comment]
Queda hacer que se guarden las etiquetas

**Comment by helogargon** [comment]
Los únicos links que quedan son los de ir a un post mediante las etiquetas creo

**Comment by albertoosdev** [comment]
Solo quedan los enlaces de /best/month y similar cuando esten listos, a parte de los de las redes sociales
