### ISSUE TITLE
Categories for posts

### ISSUE THREAD

**Issue by ElenaMateos193** [Albert017/daw#14]

**Comment by helogargon** [comment]
introducidas algunas categorías en la navegación pero solamente eso

**Comment by helogargon** [comment]
Añadidos botones radio en addPost para seleccionar la etiqueta. Una vez seleccionados no se pueden deseleccionar, no se como hacerlo. Puedes seleccionar varios. Tenemos que hacer que nos guarde en una lista (un atributo que hay en Post que es una lista de String que me guarda las etiquetas o tags) lo que hay escrito en el placeholder (lo de dentro) de los radios seleccionados

**Comment by helogargon** [comment]
botones funcionan correctamente

**Comment by helogargon** [comment]
No se como recoger la información de los checkboxes marcados
