### ISSUE TITLE
Navegación apropiada

### ISSUE THREAD

**Issue by jjluczyn** [Albert017/daw#2]

**Comment by helogargon** [comment]
voy a poner los links a change header y avatar en los botones del perfil

**Comment by helogargon** [comment]
lo he intentado pero no se porque no me va

**Comment by helogargon** [comment]
voy a crear los request mapping necesarios en usercontroller para reportUsers, reportComments y reportPosts

**Comment by helogargon** [comment]
controladores para reportsUsers, reportsComments y reportsPosts creados en userController. Arreglado un fallo en el menú del perfil donde followers no se quedaba marcado cuando estábamos dentro.

**Comment by helogargon** [comment]
Añadidos los accesos a settings, settings password y settings notifications

**Comment by helogargon** [comment]
creo que se puede llegar ya a todas partes de la página pero no se si se me ha pasado alguna

**Comment by helogargon** [comment]
He arreglado un link en mensajes que estaba mal (index) ya que antes estaba la url html

**Comment by helogargon** [comment]
Acceso a la página de edición de un perfil donde se puede cambiar nombre de usuario, localizacion, entre otros (muchos de los atributos no existen). Añadido un botón (Edit profile ) para acceder a ella. Se puede acceder desde profile, followers, following, reportsPosts, reportsComments y reportsUsers

**Comment by helogargon** [comment]
Estoy tocando addPost

**Comment by helogargon** [comment]
Arreglando enlace Hot que está mal y añadiendo tags

**Comment by helogargon** [comment]
AddPost modificada. Arreglados enlaces mal colocados. Eliminados los botones de profile photo y header que no tiene sentido ahí; Eliminado del menú de arriba followers y followings (no pintaban nada) solamente queda Home para volver al perfil.
